name: curso-djangoRAFAEL-CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10.3
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.3
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -q pipenv codecov flake8
            pipenv sync --dev
        - name: Lint with flake8
          run: |
            pipenv run flake8 .
        - name: Codecov report
          env:
            CODECOV_TOKEN: 'db749fe9-30d2-44b4-bd61-6b00b3995b49'
          run: |
            codecov