name: curso-djangoRAFAEL-CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.3
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -q pipenv codecov flake8
        pipenv sync --dev
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names 
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics 
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide 
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Codecov report
      env:
        CODECOV_TOKEN: 'db749fe9-30d2-44b4-bd61-6b00b3995b49'
      run: |
        codecov